### ISSUE TITLE
Add option to set cipher suite(s) supported

### ISSUE THREAD

**Issue by idiotsavant** [greim/hoxy#54]
It would be great to be able to control the choice of ciphers when proxying.

I'm particularly interested in the proxy-client part of the journey, so that the proxy could negotiate a strong cipher (e.g. the tls library default list) with the origin website but I could ten force a non-Diffie Hellman cipher to be used between the proxy and the client. That would mean I could tcpdump the traffic and decrypt it, which isn't possible with DH key exchanges.

If controlling the ciphersuite on the proxy-client leg independently of the server-proxy leg is hard to implement I would settle for being able to set one overall ciphersuite setting to override the tls defaults.

Many thanks!

**Comment by greim** [comment]
If you're running in reverse proxy mode, the `tls` startup option gets passed directly to Node, so you could adapt these instructions (http://greim.github.io/hoxy/#https-reverse) by adding a [ciphers](https://iojs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener) list to it.

For direct/forward proxying, you can't override the ciphers list on the internal https server instance, but Hoxy still allows MITM decryption via trusted client CAs. Instructions: http://greim.github.io/hoxy/#intercept-https

**Comment by idiotsavant** [comment]
I've been away for a couple of days - sorry for the delay getting back to you.

I think the reverse proxy recipe should work in my situation. I'll come back if I hit any problems implementing it, but I don't see why it wouldn't work. Many thanks!
