### ISSUE TITLE
Using hoxy with express and vhost

### ISSUE THREAD

**Issue by Joqui2108** [greim/hoxy#55]
I'm trying to set a subdomain to a reverse proxy doing this:

```
var hoxy = require('hoxy');

var proxy = new hoxy.Proxy({reverse: 'http://google.com/'});

proxy.intercept({
	phase: 'response',
	mimeType: 'text/html',
	as: '$'
}, function(req, resp) {
	resp.$('title').text('proxy');
});
```

```
var express = require('express'),
	vhost = require('vhost'),
	app = express();

app.use(vhost('domain.com', function (req, res) {
	proxy.emit('request', req, res);
}));
```

Any aproach of how can I do it? As proxy.listen() simply passes its arguments to Node's server.listen() I tried to follow this example: https://www.npmjs.com/package/vhost#using-with-any-generic-request-handler

Any help is well appreciated.

**Comment by greim** [comment]
`proxy.emit('request', req, res)` won't work. I suspect you'd need to do something along the lines of:

```js
var a = proxy.address();
app.use(vhost('domain.com', function (req, res) {
  req.pipe(http.request({
    hostname: a.address,
    port: a.port,
    method: req.method,
    headers: req.headers,
    path: req.url,
  })).pipe(res);
}));
```

https://iojs.org/api/http.html#http_http_request_options_callback

Also be warned, Google will try to redirect to `https` and/or a `www` url. So you'll likely need to update the reverse proxy target to avoid that.
