### ISSUE TITLE
Unable to pass other data instead of reverse-proxy data.

### ISSUE THREAD

**Issue by Joqui2108** [greim/hoxy#59]
I have something like:

```js
var proxy = hoxy.createServer({reverse: 'http://website.com'}).listen(8080);

proxy.intercept({
	phase: 'response',
	url: /.*\.pdf/,
	as: 'buffer'
}, function(req, resp, cycle) {
	download(req.url, function (file, headers) {
		resp.headers = headers;
		resp.buffer = file;
	});
});
```

and a function which downloads the file and replace the headers and the buffer with the downloaded data. And to acces the proxy I have a http.request passing the request data to hoxy. But it sends the original reversed-webpage insted of the downloaded data with the download function.

I've been trying things for hours a couldn't find a way to do it. Please help :smiley:

**Comment by greim** [comment]
Your interceptor callback needs to return a promise, otherwise hoxy won't wait for your download function to finish.

```js
proxy.intercept({
    phase: 'response',
    url: /.*\.pdf/,
    as: 'buffer'
}, function(req, resp, cycle) {
    return new Promise(function(resolve, reject) { // returning a promise pauses hoxy
        download(req.url, function (file, headers) {
            resp.headers = headers;
            resp.buffer = file;
            resolve(); // resolving the promise un-pauses hoxy
        });
    });
});
```

Hope that helps!
