### ISSUE TITLE
Promise dependency seams to fail

### ISSUE THREAD

**Issue by aemonge** [greim/hoxy#63]
```javascript
node HttpsProxyAgent.js

/home/aemonge/user/studies/mongoose/node_modules/hoxy/node_modules/co/index.js:50
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at Proxy.co (/home/aemonge/user/studies/mongoose/node_modules/hoxy/node_modules/co/index.js:50:14)
    at Server.<anonymous> (/home/aemonge/user/studies/mongoose/node_modules/hoxy/lib/proxy.js:244:23)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2109:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1967:22)
    at TCP.onread (net.js:528:27)
```

**Comment by editedredx** [comment]
What version of node are you running?

**Comment by aemonge** [comment]
```bash
aemonge@FHFXTY1 ~/u/s/mongoose> node -e 'console.log(process.versions.v8);'                                               master↓-!?
3.14.5.9
aemonge@FHFXTY1 ~/u/s/mongoose> node --version                                                                            master↓-!?
v0.10.37
aemonge@FHFXTY1 ~/u/s/mongoose> npm --version                                                                             master↓-!?
1.4.28
```

**Comment by editedredx** [comment]
Well, there you have it. [Hoxy dependency co needs a newer version of node.](https://www.npmjs.com/package/co#platform-compatibility)

**Comment by aemonge** [comment]
Got it !!!! Yei !!!! Thaks a LOT men !!!

By the way, I'm trying to log ( and store in mongoose ) all request to :5000 port, creating a proxy (or inversed one, don't really know the difference). What Incantiation would you recomend me to start with.

**Comment by greim** [comment]
> By the way, I'm trying to log ( and store in mongoose ) all request to :5000 port, creating a proxy (or inversed one, don't really know the difference). What Incantiation would you recomend me to start with. 

Try creating a reverse proxy to `yourmachine:5000`, then in the intercept handler just console.log anything you want. Hope that helps!

**Comment by aemonge** [comment]
Thanks !!!!! Go it !!! (:
