### ISSUE TITLE
Feature request: convenience property to get query parameters

### ISSUE THREAD

**Issue by mitchhentges** [greim/hoxy#73]
In the documentation for [`request.params`](http://greim.github.io/hoxy/#request-params), it's mentioned that:
> Note, parameters from the URL querystring are not included in this object. 

Is there a convenient way to get the parameters from the URL querystring?

**Comment by greim** [comment]
No built-in way to do that. Just use Node's [`url.parse()`](https://nodejs.org/dist/latest-v4.x/docs/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost) function.

```js
var url = require('url');
proxy.intercept('request', function(req, resp, cycle) {
  var parsedUrl = url.parse(req.url, true);
  console.log(parsedUrl.query);
});
```

**Comment by greim** [comment]
Sorry, didn't realize this was a feature request. Reopening.

**Comment by mitchhentges** [comment]
Actually, didn't realise how easy it was to do in node. Maybe it doesn't
fall under hoxy's jurisdiction? Feel free to close, unless you think it
would be a good addition

**Comment by greim** [comment]
I was already thinking about adding this and it's pretty easy to do.

**Comment by greim** [comment]
Now you can do this:

```js
proxy.intercept('request', function(req, resp, cycle) {
  console.log(req.query);
});
```

**Comment by mitchhentges** [comment]
Wow, that was speedy! Thanks greim :)
