### ISSUE TITLE
Question: Change target of reverse proxy depending on situation

### ISSUE THREAD

**Issue by mindworker** [greim/hoxy#86]
Hi there!

First of all, `hoxy` looks like a great package, really like the straightforward way of using the interceptor! My team considers to use hoxy in production, but before that we need to know whether the following is possible:

User requests `GET domain.com/proxy?url=http://test.com/article/x`
Server will get the url, returns the contents to the user as response

User requests `POST domain.com/proxy?url=http://different-site.com/post` with payload
Server will proxy the request to different-site.com with payload and returns the response to the user.

Thanks for you help!
Long

**Comment by greim** [comment]
That should theoretically be pretty easy to do by doing:

```
if (something) {
  request.hostname = 'site.com';
} else {
  request.hostname = 'other-site.com';
}
```

Hope that helps!

**Comment by mindworker** [comment]
Hi @greim! Thanks for your answer. I have an other question:

As we want to use hoxy inside Google Cloud Function (Google's version of AWS lambda) it must work inside a request handler (as google cloud is managing the server instances). So the only thing we get is a request obj and a reposponse obj.

In the documentation I only saw that hoxy provides a server out of the box. Is it possible to let hoxy just handle a single request by passing the request and result obj down?

Thanks in advance!

**Comment by greim** [comment]
That isn't possible at this time.

**Comment by vilcuRob** [comment]
Hi @greim, 
Congrats for this great package!

Sorry to comment on this closed issue but I'm struggling to find any ways of making this work.
Here is my code:

```
var hoxy = require('hoxy');
var domainName = 'https://www.foo.com';
var port = process.env.PORT || 8000;
var proxy = hoxy.createServer({ reverse: domainName }).listen(port, function () {
    console.log('The proxy is listening on port ' + port + '.');
});
proxy.intercept('request', function(req, resp) {
    if(req.headers.referer.indexOf('?view=bar.com')){
        req.hostname = 'https://www.bar.com';
    }
});
```

And this is what i'm trying to archive:
Navigate to localhost:8000 -> see the https://www.foo.com (as default)
Navigate to localhost:8000/?view=bar.com -> see the https://www.bar.com

Is there already a build in functionality that i'm missing?

Thanks!

**Comment by greim** [comment]
A couple things:

 * If I understand correctly, `referer` isn't the right way to do it. Use `req.url` instead.
 * Don't include `https://` in `req.hostname`. To set protocol use `req.protocol`.

Hope that helps!
