### ISSUE TITLE
How to proxy multiple subdomains

### ISSUE THREAD

**Issue by joaomilho** [greim/hoxy#96]
After going through the docs I couldn't find a way to proxy multiple subdomains except for having multiple ports reversing each. In #55 you mention "Google will try to redirect to https and/or a www url. So you'll likely need to update the reverse proxy target to take that into account". Can you elaborate?

Thanks in advance. Great work here!

**Comment by greim** [comment]
You mean like a load balancer that does some kind of round robin or random selection among a set of destination hostnames?

**Comment by joaomilho** [comment]
Not really, I just wanna reverse proxy all subdomains for a domain.

**Comment by greim** [comment]
I still don't understand. You want a single proxy server standing in front of many subdomains, acting as a reverse proxy? How does it know which subdomain to send a given request to?

**Comment by joaomilho** [comment]
my bad, what I needed was a general proxy that looks into all reqs to a domain. Solved now, thanks!
